Repository vkamiansky/fls-practice-dec-2018, pull requests merged in 2018-12, with the labels that each got.

#9 1# Мною был создан solution проекта UWP.
  TaskList/App.xaml
  TaskList/App.xaml.cs
  TaskList/Assets/LockScreenLogo.scale-200.png
  TaskList/Assets/SplashScreen.scale-200.png
  TaskList/Assets/Square150x150Logo.scale-200.png
  TaskList/Assets/Square44x44Logo.scale-200.png
  TaskList/Assets/Square44x44Logo.targetsize-24_altform-unplated.png
  TaskList/Assets/StoreLogo.png
  TaskList/Assets/Wide310x150Logo.scale-200.png
  TaskList/MainPage.xaml
  TaskList/MainPage.xaml.cs
  TaskList/Package.appxmanifest
  TaskList/Properties/AssemblyInfo.cs
  TaskList/Properties/Default.rd.xml
  TaskList/TaskList.csproj
  TaskList/TaskList.sln
Labels: groundwork

#11 #2 Добавила проект TaskList.Interface
  TaskList.Interface/TaskList.Interface.sln
  TaskList.Interface/TaskList.Interface/IRepository.cs
  TaskList.Interface/TaskList.Interface/IService.cs
  TaskList.Interface/TaskList.Interface/IView.cs
  TaskList.Interface/TaskList.Interface/IViewModel.cs
  TaskList.Interface/TaskList.Interface/TaskList.Interface.csproj
Labels: groundwork

#13 Создан проект TaskList.Servise
  .gitattributes
  TaskList.Servise/TaskList.Servise.sln
  TaskList.Servise/TaskList.Servise/Class1.cs
  TaskList.Servise/TaskList.Servise/Properties/AssemblyInfo.cs
  TaskList.Servise/TaskList.Servise/Properties/TaskList.Servise.rd.xml
  TaskList.Servise/TaskList.Servise/TaskList.Servise.csproj
Labels: groundwork

#19 Изменена структура папок, добавлены проекты в решение
  TaskList/TaskList.sln
  UWP/TaskList.DataModel/Class1.cs
  UWP/TaskList.DataModel/TaskList.DataModel.csproj
  UWP/TaskList.Interface/TaskList.Interface.sln
  UWP/TaskList.Interface/TaskList.Interface/IRepository.cs
  UWP/TaskList.Interface/TaskList.Interface/IService.cs
  UWP/TaskList.Interface/TaskList.Interface/IView.cs
  UWP/TaskList.Interface/TaskList.Interface/IViewModel.cs
  UWP/TaskList.Interface/TaskList.Interface/TaskList.Interface.csproj
  UWP/TaskList.Model/Class1.cs
  UWP/TaskList.Model/TaskList.Model.csproj
  UWP/TaskList.Servise/TaskList.Servise.sln
  UWP/TaskList.Servise/TaskList.Servise/Class1.cs
  UWP/TaskList.Servise/TaskList.Servise/Properties/AssemblyInfo.cs
  UWP/TaskList.Servise/TaskList.Servise/Properties/TaskList.Servise.rd.xml
  UWP/TaskList.Servise/TaskList.Servise/TaskList.Servise.csproj
  UWP/TaskList.sln
  UWP/TaskList/App.xaml
  UWP/TaskList/App.xaml.cs
  UWP/TaskList/Assets/LockScreenLogo.scale-200.png
  UWP/TaskList/Assets/SplashScreen.scale-200.png
  UWP/TaskList/Assets/Square150x150Logo.scale-200.png
  UWP/TaskList/Assets/Square44x44Logo.scale-200.png
  UWP/TaskList/Assets/Square44x44Logo.targetsize-24_altform-unplated.png
  UWP/TaskList/Assets/StoreLogo.png
  UWP/TaskList/Assets/Wide310x150Logo.scale-200.png
  UWP/TaskList/MainPage.xaml
  UWP/TaskList/MainPage.xaml.cs
  UWP/TaskList/Package.appxmanifest
  UWP/TaskList/Properties/AssemblyInfo.cs
  UWP/TaskList/Properties/Default.rd.xml
  UWP/TaskList/TaskList.csproj
Labels: bug

#23 Добавлен TaskList.Integration
  TaskList.Integration.sln
  TaskList.Integration/CompositionRoot.cs
  TaskList.Integration/TaskList.Integration.csproj
Labels: groundwork

#22 Features/4 add task list.view model
  UWP/TaskList.Interface/TaskList.Interface/IMainViewModel.cs
  UWP/TaskList.Interface/TaskList.Interface/INavigationService.cs
  UWP/TaskList.ViewModel/MainViewModel.cs
  UWP/TaskList.ViewModel/TaskList.ViewModel.csproj
  UWP/TaskList.sln
Labels: groundwork

#21 #15 fix bug
  UWP/TaskList.Service/NavigationService.cs
  UWP/TaskList.Service/TaskList.Service.csproj
  UWP/TaskList.Servise/TaskList.Servise.sln
  UWP/TaskList.Servise/TaskList.Servise/Class1.cs
  UWP/TaskList.Servise/TaskList.Servise/Properties/AssemblyInfo.cs
  UWP/TaskList.Servise/TaskList.Servise/Properties/TaskList.Servise.rd.xml
  UWP/TaskList.Servise/TaskList.Servise/TaskList.Servise.csproj
  UWP/TaskList.sln
Labels: bug

#12 Создал проект TaskList.View
  UWP/TaskList.View/TaskList.View.sln
  UWP/TaskList.View/TaskList.View/Class1.cs
  UWP/TaskList.View/TaskList.View/TaskList.View.csproj
  UWP/TaskList.sln
Labels: groundwork

#41 #39 View исправлен
  UWP/TaskList.View/TaskList.View.csproj
  UWP/TaskList.View/TaskList.View.sln
  UWP/TaskList.View/View.cs
Labels: enhancement, groundwork

#49 Смена типа библиотеки TaskList.Service (финальная версия навигации)
  UWP/TaskList.Service/NavigationService.cs
  UWP/TaskList.Service/Properties/AssemblyInfo.cs
  UWP/TaskList.Service/Properties/TaskList.Service.rd.xml
  UWP/TaskList.Service/TaskList.Service.csproj
  UWP/TaskList.sln
  UWP/TaskList/TaskList.csproj
Labels: bug

#58 #16 Added control solution at the root of repository.
  Control/Control.sln
  Control/Control/App.xaml
  Control/Control/App.xaml.cs
  Control/Control/Assets/LockScreenLogo.scale-200.png
  Control/Control/Assets/SplashScreen.scale-200.png
  Control/Control/Assets/Square150x150Logo.scale-200.png
  Control/Control/Assets/Square44x44Logo.scale-200.png
  Control/Control/Assets/Square44x44Logo.targetsize-24_altform-unplated.png
  Control/Control/Assets/StoreLogo.png
  Control/Control/Assets/Wide310x150Logo.scale-200.png
  Control/Control/Control.csproj
  Control/Control/GradientPlanePicker.xaml
  Control/Control/GradientPlanePicker.xaml.cs
  Control/Control/MainPage.xaml
  Control/Control/MainPage.xaml.cs
  Control/Control/Package.appxmanifest
  Control/Control/Properties/AssemblyInfo.cs
  Control/Control/Properties/Default.rd.xml
  Control/Control/ViewModel/TestViewModel.cs
Labels: Control-stars, groundwork

#59 features/53 add test task list view model
  UWP/TaskList.Interface/ITestTaskListViewModel.cs
  UWP/TaskList.Interface/IViewModel.cs~master
  UWP/TaskList.Model/TaskModel.cs
  UWP/TaskList.ViewModel/TestTaskListViewModel.cs
Labels: groundwork, happy-navigation

#60 #57 #55 Созданы интерфейсы и тест-проект, подправлена навигация
  UWP/TaskList.Data/TaskList.Data.csproj
  UWP/TaskList.Data/TaskRepository.cs
  UWP/TaskList.DataModel/Class1.cs
  UWP/TaskList.DataModel/DataModelTask.cs
  UWP/TaskList.Interface/ITaskInfoViewModel.cs
  UWP/TaskList.Interface/ITaskListViewModel.cs
  UWP/TaskList.Service/TaskList.Service.csproj
  UWP/TaskList.ViewModel.Test/TaskList.ViewModel.Test.csproj
  UWP/TaskList.ViewModel.Test/UnitTest1.cs
  UWP/TaskList.ViewModel/NewTaskViewModel.cs
  UWP/TaskList.ViewModel/TaskListVewModel.cs
  UWP/TaskList.sln
  UWP/TaskList/CompositionRoot.cs
  UWP/TaskList/TaskList.csproj
Labels: Control-stars, Urgent, enhancement, groundwork

#63 #62 Bug регистрации ViewModel.
  UWP/TaskList/CompositionRoot.cs
Labels: Control-stars, Urgent, bug, groundwork

#68 Develop/view
  Control/Control.sln
  Control/Control/App.xaml
  Control/Control/App.xaml.cs
  Control/Control/Assets/LockScreenLogo.scale-200.png
  Control/Control/Assets/SplashScreen.scale-200.png
  Control/Control/Assets/Square150x150Logo.scale-200.png
  Control/Control/Assets/Square44x44Logo.scale-200.png
  Control/Control/Assets/Square44x44Logo.targetsize-24_altform-unplated.png
  Control/Control/Assets/StoreLogo.png
  Control/Control/Assets/Wide310x150Logo.scale-200.png
  Control/Control/Control.csproj
  Control/Control/MainPage.xaml
  Control/Control/Package.appxmanifest
  Control/Control/Properties/AssemblyInfo.cs
  Control/Control/Properties/Default.rd.xml
  UWP/TaskList.Interface/ITaskListViewModel.cs
  UWP/TaskList.Interface/ITestTaskListViewModel.cs
  UWP/TaskList.Interface/PageKeys.cs
  UWP/TaskList.Model/TaskModel.cs
  UWP/TaskList.ViewModel/TaskInfoViewModel.cs
  UWP/TaskList.ViewModel/TestTaskListViewModel.cs
  UWP/TaskList/App.xaml.cs
  UWP/TaskList/GradientPlanePicker.xaml
  UWP/TaskList/GradientPlanePicker.xaml.cs
  UWP/TaskList/TaskList.csproj
  UWP/TaskList/TestViewModel.cs
  UWP/TaskList/TestViewModel/TestNewTaskViewModel.cs
  UWP/TaskList/TestViewModel/TestTaskListViewModel.cs
  UWP/TaskList/View/NewTaskPage.xaml
  UWP/TaskList/View/NewTaskPage.xaml.cs
  UWP/TaskList/View/TaskListPage.xaml
  UWP/TaskList/View/TaskListPage.xaml.cs
Labels: enhancement, groundwork, happy-navigation

#67 #56 #57 Features/Navigation
  UWP/TaskList.Data/TaskRepository.cs
  UWP/TaskList.DataModel/DataModelTask.cs
  UWP/TaskList.DataModel/DataTask.cs
  UWP/TaskList.Interface/IService.cs
  UWP/TaskList.Interface/ITaskInfoViewModel.cs
  UWP/TaskList.Interface/ITaskRepository.cs
  UWP/TaskList.Interface/ITaskService.cs
  UWP/TaskList.Interface/IView.cs
  UWP/TaskList.Interface/IViewModel.cs
  UWP/TaskList.Interface/TaskList.Interface.csproj
  UWP/TaskList.Model/Class1.cs
  UWP/TaskList.Model/Task.cs
  UWP/TaskList.Service/ReadAllTaskService.cs
  UWP/TaskList.Service/TaskList.Service.csproj
  UWP/TaskList.Service/TaskService.cs
  UWP/TaskList.ViewModel.Test/TaskList.ViewModel.Test.csproj
  UWP/TaskList.ViewModel.Test/TestViewModel.cs
  UWP/TaskList.ViewModel.Test/UnitTest1.cs
  UWP/TaskList.ViewModel/NewTaskViewModel.cs
  UWP/TaskList.ViewModel/TaskListVewModel.cs
  UWP/TaskList.ViewModel/TaskVewModel.cs
Labels: Control-stars, enhancement, groundwork

#69 Develop/view
  UWP/TaskList.Interface/INewTaskViewModel.cs
  UWP/TaskList.Interface/ITaskInfoViewModel.cs
  UWP/TaskList.Interface/ITaskListViewModel.cs
  UWP/TaskList.Interface/ImpKey.cs
  UWP/TaskList.Interface/UrgKey.cs
  UWP/TaskList.ViewModel/MainViewModel.cs
  UWP/TaskList.ViewModel/TaskInfoViewModel.cs
  UWP/TaskList/App.xaml.cs
  UWP/TaskList/GradientPlanePicker.xaml
  UWP/TaskList/ImportanceConverter.cs
  UWP/TaskList/TaskList.csproj
  UWP/TaskList/TestViewModel/TestNewTaskViewModel.cs
  UWP/TaskList/TestViewModel/TestTaskListViewModel.cs
  UWP/TaskList/UrgencyConverter.cs
  UWP/TaskList/View/NewTaskPage.xaml
  UWP/TaskList/View/TaskListPage.xaml
Labels: enhancement, groundwork, happy-navigation

#70 /develop/view
  UWP/TaskList.ViewModel.Test/TestViewModel.cs
  UWP/TaskList.ViewModel/MainViewModel.cs
  UWP/TaskList.ViewModel/TaskInfoViewModel.cs
  UWP/TaskList/ImportanceConverter.cs
  UWP/TaskList/TestViewModel/TestTaskListViewModel.cs
  UWP/TaskList/View/TaskListPage.xaml
Labels: bug, enhancement, happy-navigation
